WebApplicationMVCTanisma/Models/Ogrenci.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebApplicationMVCTanisma.Models
{
    public class Ogrenci : IEquatable<Ogrenci>
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Öğrenci adı boş geçilemez!")]
        [StringLength(maximumLength: 20, MinimumLength = 2, ErrorMessage = "Adınız 2 ile 20 karakter aralığında olmalıdır!")]
        public string Ad { get; set; }
        [Required(ErrorMessage = "Öğrenci soyadı boş geçilemez!")]
        [StringLength(maximumLength: 20, MinimumLength = 2, ErrorMessage = "Soyadınız 2 ile 20 karakter aralığında olmalıdır!")]
        public string Soyad { get; set; }
        public DateTime? DogumTarihi { get; set; }

        public static List<Ogrenci> OgrenciListesi { get; set; } = new List<Ogrenci>();

        public static List<Ogrenci> OgrencileriGetir()
        {
            if (OgrenciListesi.Count == 0)
            {
                OgrenciListesi = new List<Ogrenci>()
            {
                new Ogrenci(){Id=1, Ad="Merve",Soyad="Akın",DogumTarihi=new DateTime(1996,04,26) },
                new Ogrenci(){Id=2, Ad="Melike",Soyad="Akın",DogumTarihi=new DateTime(1999,11,30) },
                new Ogrenci(){Id=3, Ad="Furkan",Soyad="Akın",DogumTarihi=new DateTime(2006,01,06) },
                new Ogrenci(){Id=4, Ad="Kaan Ali",Soyad="Yıldırım",DogumTarihi=new DateTime(2019,08,07) }
            };
            }
            return OgrenciListesi;
        }

        public bool Equals(Ogrenci other)
        {
            return Id == other.Id;
        }
    }
}

WebApplicationMVCTanisma/Controllers/OgrenciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplicationMVCTanisma.Models;

namespace WebApplicationMVCTanisma.Controllers
{
    public class OgrenciController : Controller
    {
        // GET: Ogrenci
        public ActionResult Listele()
        {
            List<Ogrenci> ogrList = Ogrenci.OgrencileriGetir();
            return View(ogrList);
        }
        [HttpGet]
        public ActionResult Ekle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Ekle(Ogrenci ogr)
        {
            //veri tabanı bulunmadığından Id'yi kendimiz burada oluşturuyoruz.
            var tumOgrler = Ogrenci.OgrencileriGetir();
            ogr.Id = tumOgrler.Count + 1;

            //Öğrenci eklemesi yapalım.
            Ogrenci.OgrenciListesi.Add(ogr);
            //Ekleme yapıldıktan sonra Listele Action'ına redirect olalım.

            return RedirectToAction("Listele");
        }
        [HttpGet]
        public ActionResult Guncelle(int id)
        {
            //gelen id>0 ise listede onu bulu Vİew'e gönderecek.
            if (id > 0)
            {
                Ogrenci bulunanOgr = Ogrenci.OgrenciListesi.FirstOrDefault(x => x.Id == id);
                return View(bulunanOgr);
            }
            return View();
        }
        [HttpPost]
        public ActionResult Guncelle(Ogrenci ogr)
        {
            Ogrenci guncellenecekEskiOgr = Ogrenci.OgrenciListesi.FirstOrDefault(x => x.Id == ogr.Id);

            if (guncellenecekEskiOgr != null)
            {
                ////Öğrenciyi bulduk. Bulunan öğrenciye yeni değerler atanacak.
                //guncellenecekEskiOgr.Ad = ogr.Ad;
                // = işaretinin sağında Güncelle sayfasına girdiğimiz bilgiyi aldık ve bizdeki mevcut öğrenciye atadık.
                guncellenecekEskiOgr.Ad = ogr.Ad;
                guncellenecekEskiOgr.Soyad = ogr.Soyad;
                guncellenecekEskiOgr.DogumTarihi = ogr.DogumTarihi;
            }


            return RedirectToAction("Listele");
        }

        [HttpGet]
        public ActionResult Sil(int id)
        {
            var silinecekOgr = Ogrenci.OgrenciListesi.FirstOrDefault(x=> x.Id==id);
            return View(silinecekOgr);
        }

        [HttpPost]
        public ActionResult Sil(Ogrenci ogr)
        {
            if (ogr.Id > 0)
            {
                Ogrenci.OgrenciListesi.Remove(ogr);
            }
            return RedirectToAction("Listele");
        }

        [HttpPost]
        public ActionResult Sil2(Ogrenci ogr)
        {
            if (ogr.Id>0)
            {
                Ogrenci.OgrenciListesi.Remove(ogr);
                return Json(new { success = true });
            }
            return Json(new { success = false, error = "Beklenmedik hata oluştu!" });
        }

    }
}

WebApplicationMVCTanisma/Views/Ogrenci/Ekle.cshtml
@{
    ViewBag.Title = "Ekle";
}

<h2>Yeni Öğrenci Ekle</h2>
<br />

<form action="Ekle" method="post">
    <label>Öğrenci Adı:</label>
    <input class="form-control" type="text" name="Ad"><br />
    <label>Öğrenci Soyadı:</label><br>
    <input class="form-control" type="text" name="Soyad"> <br />
    <label>Öğrenci Doğum Tarihi:</label>
    <input class="form-control" type="date" name="DogumTarihi" /> <br />
    <input class="btn btn-lg btn-primary" style="margin-right:5px" type="submit" value="EKLE" />
    <a href="/Ogrenci/Listele" class="btn btn-default">Listeye Geri Dön</a>
</form>

WebApplicationMVCTanisma/Views/Ogrenci/Guncelle.cshtml
@using WebApplicationMVCTanisma.Models;
@model Ogrenci
@{
    ViewBag.Title = "Guncelle";
}

<h2>Öğrenciyi Güncelle</h2>
<br />

@*<form action="Guncelle" method="post">
        <label>Ad</label>
        <input type="text" name="Ad" value="@Model.Ad" class="form-control" /> <br />
        <label>Soyad</label>
        <input type="text" name="Soyad" value="@Model.Soyad" class="form-control" /> <br />
        <label>Doğum Tarihi</label>
        <input type="datetime" name="DogumTarihi" value="@Model.DogumTarihi" class="form-control" />
        <br />
        <input type="hidden" name="Id" value="@Model.Id" />
        <input type="submit" class="btn btn-primary" value="Güncelle" />
    </form>*@



@using (Html.BeginForm("Guncelle", "Ogrenci", FormMethod.Post))
{
    @Html.HiddenFor(x => x.Id)
    @Html.Label("Ad")
    @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Soyad)
    @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control" })
    <br />
    <label>Doğum Tarihi:</label>
    @Html.TextBoxFor(x => x.DogumTarihi, new { @class = "form-control" })
    <br />
    @*@Html.ActionLink("Güncelle", "Guncelle", "Ogrenci",
        new { }, new { @class = "btn btn-primary" })*@
    <input type="submit" class="btn btn-primary" value="Güncelle" />
}

WebApplicationMVCTanisma/Views/Ogrenci/Listele.cshtml
@using WebApplicationMVCTanisma.Models;
@{
    ViewBag.Title = "Listele";
}


@{
    ViewBag.Title = "Listele";
}

@{
    int siraNo = 0;
}
<h2>Tüm Öğrenciler</h2>
<br />

<table class="table table-hover">
    <tr>
        <th>Sıra No</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Doğum Tarihi</th>
        <th>İşlem 1</th>
        <th>İşlem 2</th>
    </tr>
    @foreach (Ogrenci item in Model)
    {
        <tr>
            <td>@(siraNo+=1)</td>
            <td>@item.Ad</td>
            <td>@item.Soyad</td>
            <td>@item.DogumTarihi.ToString("dd.MM.yyyy")</td>
            <td>
                @*<a href="Guncelle/@item.Id" class="btn btn-warning">Güncelle</a>*@
                @Html.ActionLink("Güncelle", "Guncelle", "Ogrenci", new { id = item.Id }, new { @class = "btn btn-warning" })
            </td>
            <td>
                @*<a href="Sil/@item.Id" class="btn btn-danger">Sil</a>*@

                @Html.ActionLink("Sil", "Sil", "Ogrenci", new { id = item.Id },
    new { @class = "btn btn-danger" })
                <input type="button"
                       value="Sil"
                       class="btn btn-default"
                       style="background-color:pink;"
                       onclick="ConfirmDelete(@item.Id)" />
            </td>
        </tr>
    }

</table>
<br />
<a href="/Ogrenci/Ekle" class="btn btn-success">Yeni Öğrenci Ekle</a>



<script type="text/JavaScript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>



    <script type="text/javascript">

        function ConfirmDelete(id) {
        var x = confirm("Silmek istediğinize emin misiniz?");
        if (x) {
            $.ajax({
                type: "Post",
                url: "/Ogrenci/Sil2/" + id,
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                success: function (response) {
                    alert('Silindi');
                    window.location.href = "/Ogrenci/Listele";
                },
                error: function () {
                    //alert("error");
                    alert("Beklenmedik hata oldu. Silinemedi!");
                }
            });
        }
    }
</script>

WebApplicationMVCTanisma/Views/Ogrenci/Sil.cshtml
@using WebApplicationMVCTanisma.Models
@model Ogrenci
@{
    ViewBag.Title = "Sil";
}

<h4>Öğrenci Bilgileri</h4>
<br />
<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(x => x.Ad)
    </dt>
    <dd>
        @Html.DisplayFor(x => x.Ad)
    </dd>

    <dt>
        @Html.DisplayNameFor(x => x.Soyad)
    </dt>
    <dd>
        @Html.DisplayFor(x => x.Soyad)
    </dd>
</dl>
<br />

<input type="hidden" name="@Model.Id" />
@*@Html.HiddenFor(x=>x.Id)*@ @*YUKARIDAKİ INPUT İLE AYNI AMAÇ İLE KULLANILIR.*@

@using (Html.BeginForm("Sil", "Ogrenci", FormMethod.Post))
{
    <div class="form-actions no-color">
        <input type="submit" value="Sil" class="btn btn-danger" />
    </div>
}